title: SurfPack
description: SurfPack - A ThermoTools Project
show_downloads: true
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-feed
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache

repository: "thermotools/SurfPack"
url: 'https://thermotools.github.io'
baseurl: '/SurfPack'

data_sources:
  sidebar: "sidebar.md"

includes_dir: _includes

pypi_url: 'https://pypi.org/project/surfpack/'
github:
  repository: "https://github.com/thermotools/SurfPack"
  zip_url: "https://github.com/thermotools/SurfPack/archive/refs/heads/main.zip"
